on:
  schedule:
    - cron: '0 5 * * *'
  push:
    branches: [ develop ]

jobs:
  build:
    name: Run integration tests
    uses: ./.github/workflows/it-template.yaml
    with:
      module-name: xchange-kraken
