on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: ${{ github.event_name == 'push' }}

jobs:
  build:
    name: Run integration tests
    uses: ./.github/workflows/it-template.yaml
    with:
      module-name: xchange-kraken
